export const ROUTES = {
  Home: "/",
  About: "/about",
  CreateForm: "/create-form",
  Workflows: "/workflows",
  AddApprovers: "/add-approvers",
  AddPermission: "/add-permission",
  SelectStep: "/selectStep",
  CreateProcess: "/createProcess",
  Login: "/login",
  addUser: "/users/add",
  getUser: "/users",
  getItems: "/getItems",
  getProcess: "/getprocess",
  editProcess: "/editprocess",
  Formedit: "/formedit",
  Dashboard: {
    Home: "/dashboard/home",
  },
  getApprovalRequests: "/getApprovalRequests",
  editApproval:"/editApproval",
  getInputRequests: "/getInputRequests",
  editInputRequests:"/editInputRequests",
  yourApplications:"/yourApplications"
};
